// ============================================================
//  DADOS REAIS — Agenda Clínica GRO Saúde (a partir de Jun/2026)
//  Importado da planilha: AGENDA CLINICA GRO SAUDE
//  Cada linha = um procedimento/exame realizado ou agendado.
//  Atualize tornando a planilha pública e clicando 'Sincronizar'.
// ============================================================

const GRO_EXAMES = [
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Colhe", paciente:"Antônio Campelo Silva", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Colhe", paciente:"Antônio Campelo Silva", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Colhe", paciente:"Antônio Campelo Silva", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Eletroencefalograma", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Toxicológico", empresa:"Abs", paciente:"Jose Cassio Da Costa", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Eletrocardiograma", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Ige, Grupo Especifico - Abelha", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Ige, Grupo Especifico - Marimbondo", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Ige, Grupo Especifico - Vespa", empresa:"Bem Care", paciente:"Maisa Ziviani Alves", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Conceito Turbos", paciente:"Gabriel Aparecido De Souza", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Demissional", descricao:"Acuidade Visual", empresa:"Conceito Turbos", paciente:"Gabriel Aparecido De Souza", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Priteo", paciente:"Joao Gabriel Dos Santos Jordao", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Priteo", paciente:"Joao Gabriel Dos Santos Jordao", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Montreal", paciente:"Isabel Maria Da Silva Temetro", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Montreal", paciente:"Isabel Maria Da Silva Temetro", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Moacir Constantino (Lm Engtec)", paciente:"Ricardo Cesar Ferreira", status:"Reagendado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Moacir Constantino (Lm Engtec)", paciente:"Ricardo Cesar Ferreira", status:"Reagendado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Bruna Fabiana Dos Santos", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Bruna Fabiana Dos Santos", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Camila Naiara De Paula", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Camila Naiara De Paula", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Elaine Malachias", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Elaine Malachias", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Josias Ferreira Passareli", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Josias Ferreira Passareli", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Kassia Vitoria Ferreira Da Silva", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Kassia Vitoria Ferreira Da Silva", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Luzia Aparecida Nascimento", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Luzia Aparecida Nascimento", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Faltou" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Wcunha", paciente:"Carlos Alberto Da Silva Brandao", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Sesma", paciente:"Bruna Daniela Marques Da Silva", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Rodrigo Guina", paciente:"Luam Araujo De Oliveira", status:"Realizado" },
  { data:"2026-06-01", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Rodrigo Guina", paciente:"Lucas Araujo De Oliveira", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Moacir Constantino (Lm Engtec)", paciente:"Ricardo Cesar Ferreira", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Moacir Constantino (Lm Engtec)", paciente:"Ricardo Cesar Ferreira", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Raio-X", empresa:"Maximus", paciente:"Carina Andrade Dos Santos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Femaju", paciente:"Wellington De Souza", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Aline Beatriz Damasceno Picao", status:"Faltou" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Ana Paula Da Silva", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Debora Caetano Da Silva", status:"Faltou" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Jean Carlos Silva De Paula", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Kesia Cristinia Da Silva", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Tostes Locações Ltda", paciente:"Thalita Xavier Carvalho", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Sao Francisco", paciente:"Yasmin Vitoria De Sousa Simoes", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Sao Francisco", paciente:"Yasmin Vitoria De Sousa Simoes", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Deck", paciente:"Gabriela Maria Pereira", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Deck", paciente:"Adriano Gabriel De Oliveira", status:"Faltou" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Mult Grama", paciente:"Ghleicher Balbino De Souza", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Dinamometria", empresa:"Mult Grama", paciente:"Ghleicher Balbino De Souza", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Biofisic", paciente:"Lorenzo Machado De Sousa", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Biofisic", paciente:"Bianca Mantoanelli Passos", status:"Realizado" },
  { data:"2026-06-02", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Biofisic", paciente:"Rosemeire Angela De Souza Tobias", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Abs", paciente:"Luis Gustavo Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Abs", paciente:"Luis Gustavo Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Abs", paciente:"Luis Gustavo Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Avaliação Psicossocial", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Eletrocardiograma", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Eletroencefalograma", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Raio-X", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Brasilquimica", paciente:"Marcos Antonio Pedersoli", status:"Agendado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Coplana", paciente:"Jose Renato Bertuqui", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Coplana", paciente:"Jose Renato Bertuqui", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Coplana", paciente:"Jose Renato Bertuqui", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Gama GT", empresa:"Coplana", paciente:"Jose Renato Bertuqui", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Coplana", paciente:"Jose Renato Bertuqui", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Dmw Engenharia", paciente:"Jose Marcelo Alves Chaves", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Maximus", paciente:"Daniel Vinicius De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Maximus", paciente:"Daniel Vinicius De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Maximus", paciente:"Daniel Vinicius De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Maximus", paciente:"Daniel Vinicius De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Maximus", paciente:"Daniel Vinicius De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Raio-X", empresa:"Maximus", paciente:"Daniel Vinicius De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Trama", paciente:"Cyntia Silva Gouvea", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Trama", paciente:"Cyntia Silva Gouvea", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Luciana Mara Avelar", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Maria Izabel Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Michelle Cristina Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Ricardo Garcia De Sousa", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Rosiane Aparecida Da Cruz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Camila Naiara De Paula", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Camila Naiara De Paula", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Elaine Malachias", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gharra", paciente:"Elaine Malachias", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Aline Beatriz Damasceno Picao", status:"Faltou" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Debora Caetano Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Center Pao", paciente:"Poliana Barbieri Hanna", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Trama", paciente:"Brenda Fernanda Costa", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Trama", paciente:"Brenda Fernanda Costa", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Trama", paciente:"Cristiane Aparecida Pereira Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Trama", paciente:"Cristiane Aparecida Pereira Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Trama", paciente:"Tamiris Da Silva Araujo", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Trama", paciente:"Tamiris Da Silva Araujo", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Digisystem", paciente:"Edson Martins Dos Santos", status:"Faltou" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Nagitec", paciente:"Fernando Carlos De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Nagitec", paciente:"Fernando Carlos De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"M\\&F Capital", paciente:"Luis Miguel Correia Assunção", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Colinesterase", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Eletrocardiograma", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Eletroencefalograma", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Rodrigo Guina", paciente:"Valter Reginaldo Rodrigues Dos Santos", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Dz", paciente:"Francisco Sidney Silva Neto", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Dz", paciente:"Francisco Sidney Silva Neto", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Dz", paciente:"Francisco Sidney Silva Neto", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Dz", paciente:"Danilo Marcos De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Dz", paciente:"Danilo Marcos De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Dz", paciente:"Danilo Marcos De Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Brasilquimica", paciente:"Maria Julia Alves Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Jpg", paciente:"Thiago De Freitas", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Jpg", paciente:"Thiago De Freitas", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Carbon Calhas", paciente:"Viviane Helena Domingos Montana", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Carbon Calhas", paciente:"Viviane Helena Domingos Montana", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Sandra Cristina Neves", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Shirlei Jesus De Araujo", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Simone Vacari Tavares Leandro", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Tauane Carolina Pavao", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Thais Cristina Bressan", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Valdice Da Silva Oliveira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Care Plus", paciente:"Camila Silva Ribeiro", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Care Plus", paciente:"Camila Silva Ribeiro", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Colesterol Hdl", empresa:"Care Plus", paciente:"Camila Silva Ribeiro", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Colesterol Ldl", empresa:"Care Plus", paciente:"Camila Silva Ribeiro", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Taina Gomes Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Gharra", paciente:"Taina Gomes Da Silva", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Lizote", paciente:"Michel Augusto Araujo Almeida", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Brasilquimica", paciente:"Deise Alessandra Paziani", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Brasilquimica", paciente:"Deise Alessandra Paziani", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Fast Seg", paciente:"Leandro Patrocinio De Freitas", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Ghr", paciente:"Daniela Aparecida Pupin", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Ghr", paciente:"Daniela Aparecida Pupin", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Ghr", paciente:"Daniela Aparecida Pupin", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Brasilquimica", paciente:"Mariane Caroline Siqueira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Brasilquimica", paciente:"Mariane Caroline Siqueira", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Priteo", paciente:"Joelma Maria Barbosa Da Paz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Priteo", paciente:"Joelma Maria Barbosa Da Paz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Priteo", paciente:"Joelma Maria Barbosa Da Paz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Hemograma", empresa:"Priteo", paciente:"Joelma Maria Barbosa Da Paz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Acido Metilhipurico", empresa:"Priteo", paciente:"Joelma Maria Barbosa Da Paz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Orto Cresol Urinario", empresa:"Priteo", paciente:"Joelma Maria Barbosa Da Paz", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Care Plus", paciente:"Daiane Stephanie Da Silva Botelho", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Care Plus", paciente:"Daiane Stephanie Da Silva Botelho", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Colesterol Hdl", empresa:"Care Plus", paciente:"Daiane Stephanie Da Silva Botelho", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Colesterol Ldl", empresa:"Care Plus", paciente:"Daiane Stephanie Da Silva Botelho", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Aline Beatriz Damasceno Picao", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Gro Saude", paciente:"Gabriela Andrade Querici", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Fundição Garra", paciente:"Renan Pinheiro De Araujo", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Fundição Garra", paciente:"Renan Pinheiro De Araujo", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Admissional", descricao:"Espirometria", empresa:"Fundição Garra", paciente:"Renan Pinheiro De Araujo", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Carbon Calhas", paciente:"Joshua Agostinho", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Carbon Calhas", paciente:"Joshua Agostinho", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Carbon Calhas", paciente:"Matheus Henrique De Lima Penholato", status:"Realizado" },
  { data:"2026-06-08", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Carbon Calhas", paciente:"Matheus Henrique De Lima Penholato", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Brasilquimica", paciente:"Gabrielle Capatto De Carvalho", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Brasilquimica", paciente:"Luiz Antonio Paiva", status:"Faltou" },
  { data:"2026-06-09", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Brasilquimica", paciente:"Luiz Antonio Paiva", status:"Faltou" },
  { data:"2026-06-09", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Hollywood", paciente:"Iris Thially Da Silva", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Lizote", paciente:"Luciano Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Lizote", paciente:"Luciano Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Lizote", paciente:"Luciano Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Vert Flora", paciente:"Jhenifer Da Silva Januario", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Vert Flora", paciente:"Jhenifer Da Silva Januario", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Vert Flora", paciente:"Jhenifer Da Silva Januario", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Colinesterase", empresa:"Vert Flora", paciente:"Jhenifer Da Silva Januario", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"R.C.S Factoring", paciente:"Barbara Vieira Dourado", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Ghr Transformadores", paciente:"Erich Nunes De Aguiar", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Ghr Transformadores", paciente:"Erich Nunes De Aguiar", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Monica Dos Santos Ferreira", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Gharra", paciente:"Monica Dos Santos Ferreira", status:"Realizado" },
  { data:"2026-06-09", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Biofisic", paciente:"Thalita Xavier Carvalho", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Avaliação Psicossocial", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Eletroencefalograma", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Raio-X", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Hemograma", empresa:"Jr", paciente:"Jose Dias", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Jf Contenções", paciente:"Carlos Eduardo Alves De Lima", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Jf Contenções", paciente:"Carlos Eduardo Alves De Lima", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"3J", paciente:"Marcio Adriano Gomes Oliveira", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"3J", paciente:"Marcio Adriano Gomes Oliveira", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Raio-X", empresa:"3J", paciente:"Marcio Adriano Gomes Oliveira", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Hollywood", paciente:"Helena Manieri Manfre", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Jr", paciente:"Israel Lima Ribeiro Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Jr", paciente:"Israel Lima Ribeiro Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Jr", paciente:"Jose Fabiano Da Silva Araujo", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Jr", paciente:"Jose Fabiano Da Silva Araujo", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Cloma", paciente:"Luis Henrique Davi", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Cloma", paciente:"Luis Henrique Davi", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Cloma", paciente:"Luis Henrique Davi", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Espirometria", empresa:"Cloma", paciente:"Luis Henrique Davi", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Cloma", paciente:"Maicon Vieira Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Cloma", paciente:"Maicon Vieira Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Cloma", paciente:"Maicon Vieira Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Espirometria", empresa:"Cloma", paciente:"Maicon Vieira Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Don Pepper", paciente:"Alex Sandro Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Coprocultura", empresa:"Don Pepper", paciente:"Alex Sandro Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Parasitológico", empresa:"Don Pepper", paciente:"Alex Sandro Dos Santos", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Gescon", paciente:"Lauana Valeria Da Cruz", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Beta Hcg", empresa:"Gescon", paciente:"Lauana Valeria Da Cruz", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Hemograma", empresa:"Gescon", paciente:"Lauana Valeria Da Cruz", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Fabiana Santos Oliveira", paciente:"Michelle Aparecida Da Silva", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Camila Guerreiro Munari", paciente:"Paloma Caroline De Oliveira Silva", status:"Faltou" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Alloy Tech", paciente:"Julio Cesar Ferranti", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Alloy Tech", paciente:"Julio Cesar Ferranti", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"3J", paciente:"Reinaldo Jose Chagas", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"3J", paciente:"Reinaldo Jose Chagas", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Raio-X", empresa:"3J", paciente:"Reinaldo Jose Chagas", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Hemograma", empresa:"3J", paciente:"Reinaldo Jose Chagas", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Fenol", empresa:"3J", paciente:"Reinaldo Jose Chagas", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Ghr Transformadores", paciente:"Silvio Antonio De Oliveira Mazzaron", status:"Faltou" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Ghr Transformadores", paciente:"Silvio Antonio De Oliveira Mazzaron", status:"Faltou" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Hollywood", paciente:"Nilce De Almeida", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Bom Trabalho", paciente:"Gabriela Andrade Querici", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Camila Guerreiro Munari", paciente:"Paloma Caroline De Oliveira Silva", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Mb Junior", paciente:"Marcos Antonio Bonjolo", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Mb Junior", paciente:"Marcos Antonio Bonjolo", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Mb Junior", paciente:"Marcos Antonio Bonjolo", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Mb Junior", paciente:"Marcos Antonio Bonjolo", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"O.J", paciente:"Luis Antonio Salomoni&#13;", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"O.J", paciente:"Luis Antonio Salomoni&#13;", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Be8 Exportacao E Importacao", paciente:"Alvaro Alves Milan", status:"Faltou" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Be8 Exportacao E Importacao", paciente:"Alvaro Alves Milan", status:"Faltou" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Protec", paciente:"Antonio Francisco Dos Santos Da Silva", status:"Realizado" },
  { data:"2026-06-11", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Protec", paciente:"Antonio Francisco Dos Santos Da Silva", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Conceito", paciente:"Wesley Alexandre Martins De Oliveira", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Conceito", paciente:"Wesley Alexandre Martins De Oliveira", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Faltou" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Eletroencefalograma", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Faltou" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Faltou" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Joceli Bendazzoli De Carvalho", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Gharra", paciente:"Joceli Bendazzoli De Carvalho", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Alloy Tech", paciente:"João Gilberto De Lima", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Alloy Tech", paciente:"João Gilberto De Lima", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Espirometria", empresa:"Alloy Tech", paciente:"João Gilberto De Lima", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Mudança de Riscos", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Daiana Carolina Bercieli Da Silva", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Drogaria Moderna", paciente:"Maria Victória Picinato", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Mm Campeis", paciente:"Michelle Mantovani", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Mudança de Riscos", descricao:"Exame Clínico", empresa:"Drogaria Moderna", paciente:"Fernanda Laura Pereira Zanetti", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Ghr", paciente:"Rosemeire Aparecida Moroti", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Ghr", paciente:"Rosemeire Aparecida Moroti", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Don Pepper", paciente:"Gustavo Pereira Merchan Tristão", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Larissa Cibele Ribeiro Dos Santos", paciente:"Geni Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Hemograma", empresa:"Larissa Cibele Ribeiro Dos Santos", paciente:"Geni Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Micologico De Unhas", empresa:"Larissa Cibele Ribeiro Dos Santos", paciente:"Geni Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Coprocultura", empresa:"Larissa Cibele Ribeiro Dos Santos", paciente:"Geni Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Parasitológico", empresa:"Larissa Cibele Ribeiro Dos Santos", paciente:"Geni Ribeiro De Souza", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Brasmed", paciente:"Isadora Beatriz", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Ghr", paciente:"Juan Raphael Gonçalves", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Ghr", paciente:"Juan Raphael Gonçalves", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Mb Junior", paciente:"Jose Carlos De Oliveira", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Mb Junior", paciente:"Jose Carlos De Oliveira", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Mb Junior", paciente:"Jose Carlos De Oliveira", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Be8 Exportacao E Importacao", paciente:"Alvaro Alves Milan", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Be8 Exportacao E Importacao", paciente:"Alvaro Alves Milan", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Teodoro", paciente:"Rainer Moreira Dos Santos", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Teodoro", paciente:"Rainer Moreira Dos Santos", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Teodoro", paciente:"Rainer Moreira Dos Santos", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Lizote", paciente:"Jhonatas Walace Teodoro", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Lizote", paciente:"Jhonatas Walace Teodoro", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Lizote", paciente:"Jhonatas Walace Teodoro", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Jpg Equipamentos", paciente:"Jonathan Homero De Lima", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Daiane Da Silva Mariano", status:"Realizado" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Ghr", paciente:"Victor Fidelis Da Silva", status:"Faltou" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Ghr", paciente:"Victor Fidelis Da Silva", status:"Faltou" },
  { data:"2026-06-15", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Trama Azul", paciente:"Tauane Larissa Valentin", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Alloy Tech", paciente:"Jhonny Herbert Barbosa Dos Santos", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Alloy Tech", paciente:"Jhonny Herbert Barbosa Dos Santos", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gaspar", paciente:"José Donizeti Mendes", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gaspar", paciente:"José Donizeti Mendes", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Gaspar", paciente:"José Donizeti Mendes", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Colinesterase", empresa:"Gaspar", paciente:"José Donizeti Mendes", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gaspar", paciente:"João Donizeti Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gaspar", paciente:"João Donizeti Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Gaspar", paciente:"João Donizeti Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Colinesterase", empresa:"Gaspar", paciente:"João Donizeti Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Ghr", paciente:"Victor Fidelis Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Ghr", paciente:"Victor Fidelis Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Conceito", paciente:"Joao Carlos Augusto De Melo", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Conceito", paciente:"Joao Carlos Augusto De Melo", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Conceito", paciente:"Joao Carlos Augusto De Melo", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Conceito", paciente:"Joao Carlos Augusto De Melo", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Lizote", paciente:"Edvaldo Antonio Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Audiometria", empresa:"Lizote", paciente:"Edvaldo Antonio Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Glicemia", empresa:"Lizote", paciente:"Edvaldo Antonio Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Don Pepper", paciente:"Carlos José Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Coprocultra", empresa:"Don Pepper", paciente:"Carlos José Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Admissional", descricao:"Parasitológico", empresa:"Don Pepper", paciente:"Carlos José Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Teodoro", paciente:"Miraldo Ramos Da Silva", status:"Realizado" },
  { data:"2026-06-16", tipo:"ASO Periódico", descricao:"Acuidade Visual", empresa:"Teodoro", paciente:"Miraldo Ramos Da Silva", status:"Realizado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gaspar", paciente:"Ademir Gonçalves", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gaspar", paciente:"Ademir Gonçalves", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Gaspar", paciente:"Ademir Gonçalves", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Colinesterase", empresa:"Gaspar", paciente:"Ademir Gonçalves", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Gaspar", paciente:"Rafael Menegali Mendes", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Gaspar", paciente:"Rafael Menegali Mendes", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Gaspar", paciente:"Rafael Menegali Mendes", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Colinesterase", empresa:"Gaspar", paciente:"Rafael Menegali Mendes", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Jumil", paciente:"Emerson Andre Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Eletroencefalograma", empresa:"Jumil", paciente:"Emerson Andre Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Avaliação Psicossocial", empresa:"Jumil", paciente:"Emerson Andre Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Jumil", paciente:"Emerson Andre Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Jr", paciente:"Valdecir Gomes Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Jr", paciente:"Valdecir Gomes Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Raio-X", empresa:"Jr", paciente:"Valdecir Gomes Da Silva", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Jr", paciente:"Marcelo Bernardo", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Jr", paciente:"Marcelo Bernardo", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Raio-X", empresa:"Jr", paciente:"Marcelo Bernardo", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Holaniscz", paciente:"Thiago Henrique Santos De Deus", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Demissional", descricao:"Audiometria", empresa:"Holaniscz", paciente:"Thiago Henrique Santos De Deus", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Demissional", descricao:"Acuidade Visual", empresa:"Holaniscz", paciente:"Thiago Henrique Santos De Deus", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Souza Arantes", paciente:"Marcia Helena Theodoro", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Flor De Maio", paciente:"Viviane Mara Moraes Nunes", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Exame Clínico", empresa:"Gescon", paciente:"Maria Eduarda Porceli", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Acuidade Visual", empresa:"Gescon", paciente:"Maria Eduarda Porceli", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Coprocultura", empresa:"Gescon", paciente:"Maria Eduarda Porceli", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Parasitológico De Fezes", empresa:"Gescon", paciente:"Maria Eduarda Porceli", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Hemograma", empresa:"Gescon", paciente:"Maria Eduarda Porceli", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Admissional", descricao:"Micológico De Unhas", empresa:"Gescon", paciente:"Maria Eduarda Porceli", status:"Agendado" },
  { data:"2026-06-17", tipo:"ASO Periódico", descricao:"Toxicológico", empresa:"Rizzo", paciente:"Luis Fernando Crispim", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Eletrocardiograma", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Eletroencefalograma", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Avaliação Psicossocial", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Glicemia", empresa:"Jumil", paciente:"Douglas Rafael Saltarelli", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Jr", paciente:"Joao Paulo Bernardo", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Audiometria", empresa:"Jr", paciente:"Joao Paulo Bernardo", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Raio-X", empresa:"Jr", paciente:"Joao Paulo Bernardo", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Mega Impress", paciente:"Ellen Da Rocha Giannoni", status:"Agendado" },
  { data:"2026-06-18", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Abs Infraestrutura", paciente:"José Angelo Silva Santos", status:"Agendado" },
  { data:"2026-06-19", tipo:"ASO Periódico", descricao:"Exame Clínico", empresa:"Conceito", paciente:"Glecio Jose Melo Da Silva", status:"Agendado" },
  { data:"2026-06-19", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Offelius Rest. E Choperia", paciente:"Livia Laula De Souza", status:"Agendado" },
  { data:"2026-06-19", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Gharra", paciente:"Ana Julia Fernandes Tostes", status:"Agendado" },
  { data:"2026-06-19", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Trama Azul", paciente:"Bruna Sebastiana Guidetti", status:"Agendado" },
  { data:"2026-06-22", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Trama Azul", paciente:"Helena Marcia Tiburcio Salgado", status:"Agendado" },
  { data:"2026-06-23", tipo:"ASO Demissional", descricao:"Exame Clínico", empresa:"Conceito", paciente:"Luis Fernando", status:"Agendado" },
];
